local runner = require("dockyard.commands.runner")
local config = require("dockyard.config")

local function wait_done(job)
	vim.wait(10000, function()
		return job.status ~= "running"
	end, 10)
	truthy(job.status ~= "running", "job never finished: " .. job.title)
end

local function sh(script, spec)
	return runner.start(vim.tbl_extend("force", { argv = { "sh", "-c", script } }, spec or {}))
end

describe("runner.start", function()
	it("keeps the output of stdout and stderr and marks success", function()
		local job = sh("echo one; echo two >&2")
		wait_done(job)
		eq("ok", job.status)
		eq(0, job.code)
		table.sort(job.lines)
		eq({ "one", "two" }, job.lines)
		truthy(job.ended_at >= job.started_at)
	end)

	it("marks a non-zero exit as failed and keeps the code", function()
		local job = sh("echo boom >&2; exit 3")
		wait_done(job)
		eq("failed", job.status)
		eq(3, job.code)
		eq({ "boom" }, job.lines)
	end)

	it("does not lose the last line when it has no newline", function()
		local job = sh("printf 'a\\nb'")
		wait_done(job)
		eq({ "a", "b" }, job.lines)
	end)

	it("does not lose output that arrives just before the exit", function()
		local job = sh("seq 1 20000")
		wait_done(job)
		eq(20000, #job.lines + job.omitted)
		eq("20000", job.lines[#job.lines])
	end)

	it("reassembles lines split across chunks", function()
		local job = sh("printf 'hel'; sleep 0.1; printf 'lo\\nworld\\n'")
		wait_done(job)
		eq({ "hello", "world" }, job.lines)
	end)

	it("strips ANSI sequences and keeps the last write of a carriage-return line", function()
		local job = sh("printf '\\033[32mgreen\\033[0m\\nload 1%%\\rload 100%%\\n'")
		wait_done(job)
		eq({ "green", "load 100%" }, job.lines)
	end)

	it("keeps output that is not valid UTF-8", function()
		local job = sh("printf '\\377\\376 bytes\\n'")
		wait_done(job)
		eq({ "\255\254 bytes" }, job.lines)
		eq("ok", job.status)
	end)

	it("fails without throwing when the binary does not exist", function()
		local job = runner.start({ argv = { "definitely-not-a-binary-xyz" } })
		wait_done(job)
		eq("failed", job.status)
		truthy(#job.lines >= 1)
	end)

	it("calls on_exit with the finished job", function()
		local seen
		local job = sh("exit 0", {
			on_exit = function(j)
				seen = j.status
			end,
		})
		wait_done(job)
		vim.wait(1000, function()
			return seen ~= nil
		end)
		eq("ok", seen)
	end)

	it("uses the cwd and the title it is given", function()
		local dir = vim.fn.resolve(vim.fn.tempname())
		vim.fn.mkdir(dir, "p")
		local job = sh("pwd", { cwd = dir, title = "where" })
		wait_done(job)
		eq("where", job.title)
		eq({ dir }, job.lines)
	end)
end)

describe("runner registry", function()
	it("lists newest first and finds jobs by id", function()
		runner.clear_finished()
		local a = sh("exit 0")
		local b = sh("exit 0")
		wait_done(a)
		wait_done(b)
		eq({ b.id, a.id }, vim.tbl_map(function(j)
			return j.id
		end, runner.list()))
		eq(b, runner.get(b.id))
		eq(b, runner.last())
	end)

	it("evicts the oldest finished jobs past the history limit, never a running one", function()
		runner.clear_finished()
		config.options.jobs.history = 2
		local running = sh("sleep 5")
		local a = sh("exit 0")
		wait_done(a)
		local b = sh("exit 0")
		wait_done(b)
		local c = sh("exit 0")
		wait_done(c)
		vim.wait(200)
		eq("running", runner.get(running.id).status)
		eq(nil, runner.get(a.id))
		truthy(runner.get(c.id))
		runner.cancel(running.id)
		wait_done(running)
		config.options.jobs.history = 50
	end)

	it("clear_finished keeps running jobs", function()
		runner.clear_finished()
		local running = sh("sleep 5")
		local done = sh("exit 0")
		wait_done(done)
		runner.clear_finished()
		truthy(runner.get(running.id))
		eq(nil, runner.get(done.id))
		runner.cancel(running.id)
		wait_done(running)
	end)

	it("cancels a running job", function()
		local job = sh("sleep 30")
		eq(true, runner.cancel(job.id))
		wait_done(job)
		eq("cancelled", job.status)
		eq(false, runner.cancel(job.id))
	end)

	it("reruns a job with the same command", function()
		local job = sh("echo again", { title = "t" })
		wait_done(job)
		local again = runner.rerun(job.id)
		wait_done(again)
		truthy(again.id ~= job.id)
		eq(job.argv, again.argv)
		eq({ "again" }, again.lines)
		eq("t", again.title)
	end)

	it("tells the subscribers about changes", function()
		local seen = {}
		local off = runner.subscribe(function(job)
			table.insert(seen, job and job.status or "list")
		end)
		local job = sh("exit 0")
		wait_done(job)
		off()
		truthy(vim.tbl_contains(seen, "running"), vim.inspect(seen))
		truthy(vim.tbl_contains(seen, "ok"), vim.inspect(seen))
		local n = #seen
		sh("exit 0")
		vim.wait(200)
		eq(n, #seen)
	end)

	it("drops the oldest lines of a huge output and says so", function()
		local job = sh("seq 1 6000")
		wait_done(job)
		truthy(job.omitted > 0)
		local out = runner.output(job)
		truthy(out[1]:find("earlier lines omitted", 1, true), out[1])
		eq("6000", out[#out])
		eq(6000, #job.lines + job.omitted)
	end)
end)

describe("runner helpers", function()
	it("formats durations", function()
		eq("250ms", runner.format_duration(0.25))
		eq("3.2s", runner.format_duration(3.24))
		eq("1m 04s", runner.format_duration(64))
	end)

	it("formats a command line, quoting what needs it", function()
		eq("docker compose -f /p/a.yml up -d", runner.format_cmd({ "docker", "compose", "-f", "/p/a.yml", "up", "-d" }))
		eq("docker --profile '*' up", runner.format_cmd({ "docker", "--profile", "*", "up" }))
		eq("echo 'a b'", runner.format_cmd({ "echo", "a b" }))
	end)
end)
