name: Release

on:
  push:
    tags: ["*"]

jobs:
  luarocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: nvim-neorocks/luarocks-tag-release@4aa641e8e4befe0617fa3d7db40dbda832ddd27b # v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          summary: Docker dashboard, compose and Dockerfile actions inside Neovim
          labels: |
            neovim
            docker
