name: Release

on:
  push:
    tags: ["*"]

jobs:
  luarocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          summary: Docker dashboard, compose and Dockerfile actions inside Neovim
          labels: |
            neovim
            docker
